"""
db.py - SQLite helpers and graph builder.

Canonical table names (exactly as created by ingest.py from your folders):
  sales_order_headers
  sales_order_items
  sales_order_schedule_lines
  outbound_delivery_headers
  outbound_delivery_items
  billing_headers               (from billing_document_headers/)
  billing_items                 (from billing_document_items/)
  billing_cancellations         (from billing_document_cancellations/)
  payments_accounts_receivable
  journal_entry_items_accounts_receivable
  business_partners
  business_partner_addresses
  customer_company_assignments
  customer_sales_area_assignments
  products
  product_descriptions
  product_plants
  product_storage_locations
  plants
"""

import sqlite3
import pandas as pd
import os

DB_PATH  = os.path.join(os.path.dirname(__file__), "./data/graph.db")
DATA_DIR = os.path.join(os.path.dirname(__file__), "./data")


def get_conn():
    conn = sqlite3.connect(DB_PATH, check_same_thread=False)
    conn.row_factory = sqlite3.Row
    return conn


def table_exists(conn, name):
    r = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name=?", (name,)
    ).fetchone()
    return r is not None


def safe_query(conn, sql, params=()):
    try:
        return [dict(r) for r in conn.execute(sql, params).fetchall()]
    except Exception:
        return []


def init_db():
    conn = get_conn()
    tables = conn.execute("SELECT name FROM sqlite_master WHERE type='table'").fetchall()
    if not tables:
        print("  DB empty — loading sample data as fallback...")
        _load_sample_csvs(conn)
    else:
        print(f"  DB ready: {len(tables)} tables")
    conn.close()


def _load_sample_csvs(conn):
    """
    Load sample CSVs (generated by generate_sample_data.py) into the
    canonical table names that match the real SAP folder structure.
    """
    # Generate CSVs if they don't exist yet
    first_csv = os.path.join(DATA_DIR, "customers.csv")
    if not os.path.exists(first_csv):
        print("  Generating sample CSVs...")
        script = os.path.join(os.path.dirname(__file__), "../scripts/generate_sample_data.py")
        os.system(f'python3 "{script}"')

    csv_map = [
        ("customers",          "business_partners"),
        ("products",           "products"),
        ("plants",             "plants"),
        ("addresses",          "business_partner_addresses"),
        ("sales_orders",       "sales_order_headers"),
        ("sales_order_items",  "sales_order_items"),
        ("deliveries",         "outbound_delivery_headers"),
        ("invoices",           "billing_headers"),
        ("payments",           "payments_accounts_receivable"),
        ("journal_entries",    "journal_entry_items_accounts_receivable"),
    ]
    for fname, table in csv_map:
        path = os.path.join(DATA_DIR, f"{fname}.csv")
        if not os.path.exists(path):
            print(f"    ⚠  {fname}.csv not found, skipping")
            continue
        df = None
        for enc in ("utf-8", "utf-8-sig", "latin-1", "cp1252"):
            try:
                df = pd.read_csv(path, encoding=enc)
                break
            except Exception:
                continue
        if df is None:
            print(f"    ✗  {fname}.csv unreadable, regenerating...")
            os.remove(path)
            script = os.path.join(os.path.dirname(__file__), "../scripts/generate_sample_data.py")
            os.system(f'python3 "{script}"')
            try:
                df = pd.read_csv(path, encoding="utf-8")
            except Exception as e:
                print(f"    ✗  Still failed: {e}, skipping")
                continue
        df.to_sql(table, conn, if_exists="replace", index=False)
        print(f"    ✓ {table}: {len(df)} rows")
    conn.commit()


def get_schema_description():
    """Returns live schema from DB for the LLM prompt."""
    conn = get_conn()
    try:
        tables = [r[0] for r in conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name"
        ).fetchall()]
    except Exception:
        tables = []

    lines = ["DATABASE SCHEMA (SQLite):\n"]
    for t in tables:
        try:
            cols = [r[1] for r in conn.execute(f'PRAGMA table_info("{t}")').fetchall()]
            lines.append(f"  {t}({', '.join(cols)})")
        except Exception:
            continue
    conn.close()

    if not tables:
        lines.append("  (no tables loaded yet — run ingest.py first)")

    lines += [
        "",
        "KEY RELATIONSHIPS:",
        "  sales_order_headers.SalesOrder      → sales_order_items.SalesOrder",
        "  sales_order_headers.SalesOrder      → sales_order_schedule_lines.SalesOrder",
        "  sales_order_headers.SoldToParty     → business_partners.BusinessPartner",
        "  outbound_delivery_headers.DeliveryDocument → outbound_delivery_items.DeliveryDocument",
        "  billing_headers.BillingDocument     → billing_items.BillingDocument",
        "  billing_headers.BillingDocument     → billing_cancellations.BillingDocument",
        "  billing_headers.BillingDocument     → payments_accounts_receivable.BillingDocument",
        "  billing_headers.BillingDocument     → journal_entry_items_accounts_receivable.BillingDocument",
        "  sales_order_items.Material          → products.Material",
        "  outbound_delivery_headers.Plant     → plants.Plant",
        "",
        "BUSINESS FLOW:",
        "  business_partners → sales_order_headers → sales_order_items",
        "  → outbound_delivery_headers → billing_headers",
        "  → payments_accounts_receivable",
        "  → journal_entry_items_accounts_receivable",
        "",
        "BROKEN FLOW PATTERNS:",
        "  No delivery:  sales_order_headers with no matching outbound_delivery_headers",
        "  No billing:   outbound_delivery_headers with no matching billing_headers",
        "  No payment:   billing_headers with no matching payments_accounts_receivable",
        "  Cancelled:    billing_cancellations has the BillingDocument",
    ]
    return "\n".join(lines)


def run_query(sql: str):
    conn = get_conn()
    try:
        cur = conn.execute(sql)
        cols = [d[0] for d in cur.description]
        rows = [dict(zip(cols, row)) for row in cur.fetchall()]
        return rows, None
    except Exception as e:
        return None, str(e)
    finally:
        conn.close()


# ── Node type registry (table → display type, ID column) ─────────────────────

NODE_TYPE_MAP = {
    "sales_order_headers":                        ("SalesOrder",    "SalesOrder"),
    "sales_order_items":                          ("OrderItem",     "SalesOrderItem"),
    "outbound_delivery_headers":                  ("Delivery",      "DeliveryDocument"),
    "billing_headers":                            ("Invoice",       "BillingDocument"),
    "payments_accounts_receivable":               ("Payment",       "PaymentDocument"),
    "journal_entry_items_accounts_receivable":    ("JournalEntry",  "AccountingDocument"),
    "business_partners":                          ("Customer",      "BusinessPartner"),
    "products":                                   ("Product",       "Material"),
    "plants":                                     ("Plant",         "Plant"),
}


# ── Graph builder ─────────────────────────────────────────────────────────────

def get_graph_data(limit_orders=25):
    conn = get_conn()
    nodes, edges = [], []
    seen = set()

    def add_node(nid, label, ntype, props=None):
        nid = str(nid).strip()
        if nid and nid != "None" and nid not in seen:
            seen.add(nid)
            nodes.append({"id": nid, "label": str(label)[:20], "type": ntype, "properties": props or {}})

    def add_edge(src, tgt, rel):
        src, tgt = str(src).strip(), str(tgt).strip()
        if src and tgt and src != tgt and src != "None" and tgt != "None":
            edges.append({"source": src, "target": tgt, "label": rel})

    # Business Partners
    if table_exists(conn, "business_partners"):
        for r in safe_query(conn, "SELECT * FROM business_partners LIMIT 30"):
            bp  = str(r.get("BusinessPartner") or r.get("customer_id") or "")
            name = r.get("BusinessPartnerFullName") or r.get("OrganizationBPFullName") or r.get("name") or bp
            if bp: add_node(bp, name, "Customer", r)

    # Products
    if table_exists(conn, "products"):
        for r in safe_query(conn, "SELECT * FROM products LIMIT 20"):
            mat  = str(r.get("Material") or r.get("material_id") or "")
            desc = r.get("ProductDescription") or r.get("description") or mat
            if mat: add_node(mat, desc, "Product", r)

    # Plants
    if table_exists(conn, "plants"):
        for r in safe_query(conn, "SELECT * FROM plants LIMIT 10"):
            pid  = str(r.get("Plant") or r.get("plant_id") or "")
            name = r.get("PlantName") or r.get("name") or pid
            if pid: add_node(pid, name, "Plant", r)

    # Sales Order Headers
    if table_exists(conn, "sales_order_headers"):
        for r in safe_query(conn, f"SELECT * FROM sales_order_headers LIMIT {limit_orders}"):
            so   = str(r.get("SalesOrder") or r.get("sales_order_id") or "")
            cust = str(r.get("SoldToParty") or r.get("customer_id") or "")
            if not so: continue
            add_node(so, so, "SalesOrder", r)
            if cust and cust in seen: add_edge(cust, so, "PLACED")

    # Sales Order Items
    if table_exists(conn, "sales_order_items"):
        for r in safe_query(conn,
            f"""SELECT soi.* FROM sales_order_items soi
                INNER JOIN sales_order_headers soh ON soi.SalesOrder = soh.SalesOrder
                LIMIT {limit_orders * 3}"""
        ):
            so   = str(r.get("SalesOrder") or "")
            item = str(r.get("SalesOrderItem") or r.get("item_id") or "")
            mat  = str(r.get("Material") or r.get("material_id") or "")
            if so and item:
                nid = f"{so}-{item}"
                add_node(nid, f"Item {item}", "OrderItem", r)
                if so in seen:  add_edge(so, nid, "HAS_ITEM")
                if mat and mat in seen: add_edge(nid, mat, "IS_PRODUCT")

    # Outbound Delivery Headers
    if table_exists(conn, "outbound_delivery_headers"):
        for r in safe_query(conn, f"SELECT * FROM outbound_delivery_headers LIMIT {limit_orders}"):
            did   = str(r.get("DeliveryDocument") or r.get("delivery_id") or "")
            so    = str(r.get("SalesOrder") or r.get("sales_order_id") or "")
            plant = str(r.get("Plant") or r.get("ShippingPoint") or r.get("plant_id") or "")
            if not did: continue
            add_node(did, did, "Delivery", r)
            if so and so in seen:        add_edge(so, did, "DELIVERED_VIA")
            if plant and plant in seen:  add_edge(did, plant, "FROM_PLANT")

    # Billing Headers
    if table_exists(conn, "billing_headers"):
        for r in safe_query(conn, f"SELECT * FROM billing_headers LIMIT {limit_orders}"):
            bid = str(r.get("BillingDocument") or r.get("invoice_id") or "")
            did = str(r.get("DeliveryDocument") or r.get("delivery_id") or "")
            so  = str(r.get("SalesOrder") or r.get("sales_order_id") or "")
            if not bid: continue
            add_node(bid, bid, "Invoice", r)
            if did and did in seen:      add_edge(did, bid, "BILLED_AS")
            elif so and so in seen:      add_edge(so,  bid, "BILLED_AS")

    # Payments
    if table_exists(conn, "payments_accounts_receivable"):
        for r in safe_query(conn, f"SELECT * FROM payments_accounts_receivable LIMIT {limit_orders}"):
            pid = str(r.get("PaymentDocument") or r.get("payment_id") or r.get("Document") or "")
            bid = str(r.get("BillingDocument") or r.get("invoice_id") or "")
            if not pid: continue
            add_node(pid, pid, "Payment", r)
            if bid and bid in seen: add_edge(bid, pid, "SETTLED_BY")

    # Journal Entries
    if table_exists(conn, "journal_entry_items_accounts_receivable"):
        for r in safe_query(conn,
            f"SELECT * FROM journal_entry_items_accounts_receivable LIMIT {limit_orders}"
        ):
            jid = str(r.get("AccountingDocument") or r.get("journal_entry_id") or "")
            bid = str(r.get("BillingDocument") or r.get("invoice_id") or "")
            if not jid: continue
            add_node(jid, jid, "JournalEntry", r)
            if bid and bid in seen: add_edge(bid, jid, "RECORDED_AS")

    conn.close()
    return {"nodes": nodes, "edges": edges}


def get_node_neighbors(node_id: str):
    conn = get_conn()
    for table, (ntype, id_col) in NODE_TYPE_MAP.items():
        if not table_exists(conn, table):
            continue
        try:
            row = conn.execute(
                f'SELECT * FROM "{table}" WHERE "{id_col}" = ? LIMIT 1', (node_id,)
            ).fetchone()
            if row:
                conn.close()
                return {"id": node_id, "type": ntype, "properties": dict(row)}
        except Exception:
            continue
    conn.close()
    return None